import {
  Activity,
  ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  Ban,
  BarChart3,
  Bell,
  BookOpen,
  Bookmark,
  Boxes,
  Building2,
  Calendar,
  Check,
  Circle,
  CircleCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  CornerDownRight,
  Eye,
  EyeOff,
  Filter,
  Globe,
  Hash,
  HardDrive,
  Heart,
  HelpCircle,
  Image as ImageIcon,
  Inbox,
  KeyRound,
  LayoutDashboard,
  Layers,
  Lock,
  LogOut,
  type LucideIcon,
  Mail,
  Menu,
  MessageCircle,
  MessageSquare,
  MoreHorizontal,
  PenLine,
  Pin,
  Plus,
  RefreshCw,
  RotateCcw,
  Search,
  Send,
  Share2,
  SlidersHorizontal,
  ShieldAlert,
  ShieldCheck,
  SquarePen,
  Sun,
  Moon,
  Trash2,
  TrendingUp,
  TriangleAlert,
  UserCheck,
  UserPlus,
  UserRound,
  Users,
  X,
} from "lucide-react";

const ICONS = {
  // 콘솔/어드민 공용
  dashboard: LayoutDashboard,
  spaces: Boxes,
  boards: MessageSquare,
  members: Users,
  moderation: ShieldAlert,
  settings: SlidersHorizontal,
  profile: UserRound,
  bell: Bell,
  help: HelpCircle,
  search: Search,
  lock: Lock,
  globe: Globe,
  plus: Plus,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  more: MoreHorizontal,
  edit: SquarePen,
  trash: Trash2,
  check: Check,
  trendingUp: TrendingUp,
  penLine: PenLine,
  userPlus: UserPlus,
  bookmark: Bookmark,
  calendar: Calendar,
  arrowRight: ArrowRight,
  sun: Sun,
  moon: Moon,
  building: Building2,
  shieldCheck: ShieldCheck,
  shieldAlert: ShieldAlert,
  key: KeyRound,
  activity: Activity,
  filter: Filter,
  sort: ArrowDownUp,
  logout: LogOut,
  eye: Eye,
  eyeOff: EyeOff,
  ban: Ban,
  rotateCcw: RotateCcw,
  checkCircle: CircleCheck,
  dot: Circle,
  x: X,
  clock: Clock,
  hardDrive: HardDrive,
  barChart: BarChart3,
  mail: Mail,
  alertTriangle: TriangleAlert,
  userCheck: UserCheck,
  refresh: RefreshCw,
  layers: Layers,
  menu: Menu,
  // 커뮤니티 추가 아이콘
  heart: Heart,
  comment: MessageCircle,
  share: Share2,
  reply: CornerDownRight,
  send: Send,
  image: ImageIcon,
  pin: Pin,
  hash: Hash,
  book: BookOpen,
  inbox: Inbox,
  arrowLeft: ArrowLeft,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  size = 18,
  strokeWidth = 1.75,
  className,
}: {
  name: IconName;
  size?: number;
  strokeWidth?: number;
  className?: string;
}) {
  const Cmp = ICONS[name];
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} />;
}
